[tool.poetry]
name = "generative-models"
version = "0.1.0"
description = "Generative models with TensorFlow, including Generative Adversarial Networks (GAN), Diffusion Models (DM) and Variational Auto-Encoders (VAE)."
authors = ["Johan Attia"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
tensorflow = "2.8"
tensorflow-probability = "^0.17.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
